name: deploy to gh pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: |
          npm install -g pnpm
          pnpm install

      - name: Build
        run: pnpm build --base talk

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          # commit-message: ":rocket: deploy to `gh-pages`"
